
[maid_storage_manager]

	[maid_storage_manager.smithing]
		enable = true

	[maid_storage_manager.brewing]
		enable = true
		count = 3

	[maid_storage_manager.stripping]
		enable = true

	[maid_storage_manager.altar]
		enable = true

	[maid_storage_manager.furnace]
		enable = true

	[maid_storage_manager.watering]
		bucket = true
		enable = true
		bottle = true

	[maid_storage_manager.craft]
		enable = true

	[maid_storage_manager.stone_cutting]
		enable = true

[create]

	[create.crushing]
		enable = true
		count = 16

	[create.pressing]
		enable = true

	[create.fan]
		haunting = true
		splashing = true
		enable = true
		smoking = true
		count = 8
		replace_furnace = true
		blasting = true

	[create.compacting]
		enable = true

	[create.mixing]
		enable = true

	[create.deploying]
		enable = true

	[create.milling]
		enable = true

	[create.item_application]
		enable = true

